myBbcodeSettings = {
  nameSpace:          "bbcode",
  previewParserPath:  "~/sets/bbcode/preview.php",
  onEnter: false,
  markupSet:
	[
		[
			{name:'Fett', key:'B', openWith:'[b]', closeWith:'[/b]'}, 
			{name:'Kursiv', key:'I', openWith:'[i]', closeWith:'[/i]'}, 
			{name:'Unterstrichen', key:'U', openWith:'[u]', closeWith:'[/u]'}, 
			{separator:'---------------' },
			{name:'Bild', key:'P', replaceWith:'[img][![Url]!][/img]'}, 
			{name:'Link', key:'L', openWith:'[url=[![Url]!]]', closeWith:'[/url]', placeHolder:'Dein Linktext...'},
			{separator:'---------------' },
			//{newline:'---------------' },
			{name:'Farben', openWith:'[color=[![Color]!]]', closeWith:'[/color]', dropMenu: [
				{name:'Gelb', openWith:'[color=yellow]', closeWith:'[/color]', className:"col1-1" },
				{name:'Orange', openWith:'[color=orange]', closeWith:'[/color]', className:"col1-2" },
				{name:'Rot', openWith:'[color=red]', closeWith:'[/color]', className:"col1-3" },
				{name:'Blau', openWith:'[color=blue]', closeWith:'[/color]', className:"col2-1" },
				{name:'Lila', openWith:'[color=purple]', closeWith:'[/color]', className:"col2-2" },
				{name:'Gr&uuml;n', openWith:'[color=green]', closeWith:'[/color]', className:"col2-3" },
				{name:'Wei&szlig', openWith:'[color=white]', closeWith:'[/color]', className:"col3-1" },
				{name:'Grau', openWith:'[color=gray]', closeWith:'[/color]', className:"col3-2" },
				{name:'Schwarz', openWith:'[color=black]', closeWith:'[/color]', className:"col3-3" }
			]},
			{name:'Gr&ouml;&szlig;e', key:'S', openWith:'[size=[![Text size]!]]', closeWith:'[/size]', dropMenu :[
				{name:'Klein', openWith:'[size=8]', closeWith:'[/size]' },
				{name:'Normal', openWith:'[size=11]', closeWith:'[/size]' },
				{name:'Gro&szlig;', openWith:'[size=16]', closeWith:'[/size]' },
				{name:'Riesig', openWith:'[size=20]', closeWith:'[/size]' }
			]},
			{separator:'---------------' },
			{name:'Linksb&uuml;ndig', openWith:'[left]\n', closeWith:'\n[/left]'}, 
			{name:'Zentriert', openWith:'[center]\n', closeWith:'\n[/center]'}, 
			{name:'Rechtssb&uuml;ndig', openWith:'[right]\n', closeWith:'\n[/right]'}, 
			{separator:'---------------' },
			{name:'Liste', openWith:'[list]\n', closeWith:'\n[/list]'}, 
			{name:'Numerische Liste', openWith:'[list=[![Starting number]!]]\n', closeWith:'\n[/list]'}, 
			{name:'Listenfeld', openWith:'[*] '}, 
			{separator:'---------------' },
			{name:'Quote', openWith:'[quote]', closeWith:'[/quote]'}, 
			{name:'Code', openWith:'[code]', closeWith:'[/code]'}, 
			{separator:'---------------' },
			{name:'Spoiler', openWith:'[spoiler]', closeWith:'[/spoiler]'}, 
			{name:'Hidden - Diesen Text k&ouml;nnen nur Mitglieder sehen', openWith:'[hidden]', closeWith:'[/hidden]'}, 
			{separator:'---------------' },
			{name:'Youtube', openWith:'[youtube]', closeWith:'[/youtube]'}, 
			{separator:'---------------' },
			//{name:'S&auml;ubern', className:"clean", replaceWith:function(h) { return h.selection.replace(/\[(.*?)\]/g, "") } },
			{name:'Vorschau', className:"preview", call:'preview' }
		],
		[
			{name:':)', openWith:':)'}, 
			{name:';)', openWith:';)'}, 
			{name:':|', openWith:':|'}, 
			{name:':(', openWith:':('}, 
			{name:':o', openWith:':o'}, 
			{name:':p', openWith:':p'}, 
			{name:'B)', openWith:'B)'}, 
			{name:':D', openWith:':D'}, 
			{name:':@', openWith:':@'}, 
			{name:':^)', openWith:':^)'}, 
			{name:'(blush)', openWith:'(blush)'}, 
			{name:'(wasntme)', openWith:'(wasntme)'}, 
			{name:'(hihi)', openWith:'(hihi)'}, 
			{name:'(puke)', openWith:'(puke)'}, 
			{name:'(bandit)', openWith:'(bandit)'}, 
			{name:'(mooning)', openWith:'(mooning)'}, 
			{name:'(wait)', openWith:'(wait)'}, 
			{name:'(headbang)', openWith:'(headbang)'}, 
			{name:'(drunk)', openWith:'(drunk)'}, 
			{name:'(rock)', openWith:'(rock)'}, 
			{name:'(wave)', openWith:'(wave)'}, 
			{name:'(fubar)', openWith:'(fubar)'}, 
			{name:'(finger)', openWith:'(finger)'}, 
			{name:'(swear)', openWith:'(swear)'}, 
			{name:'(rofl)', openWith:'(rofl)'},
			{name:'(honk)', openWith:'(honk)'},
			{name:'(f)', openWith:'(f)'},
			{name:'(e)', openWith:'(e)'}
		]
   ]
}
